---
- name: install postgres
  yum:
    name: postgresql-server
    state: latest

- name: enable postgres at boot
  service:
    name: postgresql.service
    enabled: yes

- name: check postgres data dir
  stat: path=/var/lib/pgsql/data/postgresql.conf
  register: st

- name: initilize postgres
  command: postgresql-setup initdb
  when: not st.stat.exists

- name: restart postgres
  service:
    name: postgresql.service
    state: restarted
